config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Photo and albums routes
  scope :users do
    resources :photos, :albums, except: %i[index show]
  end
  # Profile routes
  get '/profiles/photos', to: 'profiles#personalpagephoto'
  get '/profiles/albums', to: 'profiles#personalpagealbum'
  get '/profiles/followers', to: 'profiles#personalpagefollower'
  get '/profiles/followings', to: 'profiles#personalpagefollowing'
  # Public profile routes
  get '/profiles/:id/photos', to: 'public_profiles#photo', as: 'public_photo'
  get 'profiles/:id/albums', to: 'public_profiles#album', as: 'public_album'
  get 'profiles/:id/followings', to: 'public_profiles#following', as: 'public_followings'
  get 'profiles/:id/followers', to: 'public_profiles#follower', as: 'public_followers'
  # Feeds & Discovers routes
  get 'feeds/photos', to: 'feeds#photo', as: 'feed_photos'
  get 'feeds/albums', to: 'feeds#album', as: 'feed_albums'
  get 'discover/photos', to: 'discovers#photo', as: 'discover_photos'
  get 'discover/albums', to: 'discovers#album', as: 'discover_albums'
  # follow route
  patch '/follow/unfollow/:follower_id/:followed_id', to: 'follows#unfollow', as: 'unfollow'
  patch '/follow/:follower_id/:followed_id', to: 'follows#follow', as: 'follow'
  # like post route
  post '/users/:user_id/photos/:photo_id', to: 'photos#like', as: 'like_photo'
  post '/users/:user_id/album/:album_id', to: 'albums#like', as: 'like_album'
  # manager routes
  get 'manager/photos', to: 'managers#photo', as: 'manage_photo'
  get 'manager/albums', to: 'managers#album', as: 'manage_album'
  get 'manager/users', to: 'managers#user', as: 'manage_user'
  get 'manager/users/:user_id/edit', to: 'managers#edit', as: 'manage_edit_user'
  put 'manager/users/:user_id', to: 'managers#update', as: 'manage_update_user'
  delete 'manager/users/:user_id/delete', to: 'managers#delete', as: 'manage_delete_user'

  root 'main#home'
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  def photo
    @photos = []
    Photo.find_each(batch_size: 100) do |photo|
      @photos << photo
    end
    @photos = Kaminari.paginate_array(@photos).page(params[:page]).per(40)
  end

  def album
    @albums = []
    Album.find_each(batch_size: 100) do |album|
      @albums << album
    end
    @albums = Kaminari.paginate_array(@albums).page(params[:page]).per(40)
  end

  def user
    @current_user_id = current_user.id
    @users = User.where.not(id: @current_user_id).pluck(:fname, :lname, :email, :last_sign_in_at, :id)
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(40)
  end

  def edit
    @user = User.find_by(id: params[:user_id])
  end

  def update
    @user = User.find_by(id: params[:user_id])
    if params[:password].blank?
      if @user.update(user_without_password_params)
        flash[:notice] = 'Uploaded successfully'
      else
        flash[:alert] = 'Update Failed'
      end
    else
      @user.update(user_params)
      flash[:notice] = 'Uploaded successfully'
    end
    redirect_to request.referer
  end

  def delete
    @user = User.find_by(id: params[:user_id])
    if @user.destroy
      flash[:notice] = 'Delete successfully'
    else
      flash[:alert] = 'Cannot delete user'
    end
    redirect_to request.referer
  end

  private

  def user_without_password_params
    params.require(:user).permit(:fname, :lname, :email, :activate)
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password, :activate)
  end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/partials/_album.html.erb
<div class="col-12 col-md-6 col-lg-3">
  <div class="position-relative" style="min-height: 250px">
    <%= image_tag(album.images[0].url, class: "rounded img-fluid mb-2 img-thumbnail position-absolute", style: "transform: skewY(8deg)") %>
    <%= image_tag(album.images[0].url, class: "rounded img-fluid mb-2 img-thumbnail position-absolute", style: "transform: skewY(4deg)") %>
    <%= image_tag(album.images[0].url, class: "rounded img-fluid mb-2 img-thumbnail position-absolute") %>
    <div class="position-absolute top-0 w-100 bg-dark opacity-75 d-flex align-items-center justify-content-between">
      <p class="manager-photo-title mb-0 ms-1"><%= truncate(album.title, length: 20) %></p>
      <%= link_to edit_album_path(album.id) do %>
        <%= image_tag("edit2.png", class: "me-1", style: "height: 25px; width: 25px") %>
      <% end %>
    </div>
  </div>
</div>

app/views/managers/partials/_photo.html.erb
<div class="col-12 col-md-6 col-lg-3">
  <div class="position-relative">
    <div class="position-absolute top-0 w-100 bg-dark opacity-75 d-flex align-items-center justify-content-between">
      <p class="manager-photo-title mb-0 ms-1"><%= truncate(photo.title, length: 20) %></p>
      <%= link_to edit_photo_path(photo.id) do %>
        <%= image_tag("edit2.png", class: "me-1", style: "height: 25px; width: 25px") %>
      <% end %>
    </div>
    <%= image_tag(photo.image.url, class: "rounded img-fluid mb-2") %>
  </div>
</div>

app/views/managers/partials/_user.html.erb
<tr>
  <th scope="row"><%= index + 1 %></th>
  <td><%= user[0] %></td>
  <td><%= user[1] %></td>
  <td><%= user[2] %></td>
  <td><%= user[3].in_time_zone("Asia/Ho_Chi_Minh").strftime("%I:%M %p %d/%m/%Y") %></td>
  <td class="d-flex gap-2 justify-content-center align-items-center">
    <%= button_to("Edit", manage_edit_user_path(user[4]), method: :get, class: "btn btn-success") %>
    <%= button_to("Delete", manage_delete_user_path(user[4]), method: :delete, class: "btn btn-danger") %>
  </td>
</tr>