config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Photo and albums routes
  scope :users do
    resources :photos, :albums, except: %i[index show]
  end
  # Profile routes
  get '/profiles/photos', to: 'profiles#personalpagephoto'
  get '/profiles/albums', to: 'profiles#personalpagealbum'
  get '/profiles/followers', to: 'profiles#personalpagefollower'
  get '/profiles/followings', to: 'profiles#personalpagefollowing'
  # Public profile routes
  get '/profiles/:id/photos', to: 'public_profiles#photo', as: 'public_photo'
  get 'profiles/:id/albums', to: 'public_profiles#album', as: 'public_album'
  get 'profiles/:id/followings', to: 'public_profiles#following', as: 'public_followings'
  get 'profiles/:id/followers', to: 'public_profiles#follower', as: 'public_followers'
  # Feeds & Discovers routes
  get 'feeds/photos', to: 'feeds#photo', as: 'feed_photos'
  get 'feeds/albums', to: 'feeds#album', as: 'feed_albums'
  get 'discover/photos', to: 'discovers#photo', as: 'discover_photos'
  get 'discover/albums', to: 'discovers#album', as: 'discover_albums'
  # follow route
  patch '/follow/unfollow/:follower_id/:followed_id', to: 'follows#unfollow', as: 'unfollow'
  patch '/follow/:follower_id/:followed_id', to: 'follows#follow', as: 'follow'
  # like post route
  post '/users/:user_id/photos/:photo_id', to: 'photos#like', as: 'like_photo'
  post '/users/:user_id/album/:album_id', to: 'albums#like', as: 'like_album'
  # manager routes
  get 'manager/photos', to: 'managers#photo', as: 'manage_photo'
  get 'manager/albums', to: 'managers#album', as: 'manage_album'
  get 'manager/users', to: 'managers#user', as: 'manage_user'
  get 'manager/users/:user_id/edit', to: 'managers#edit', as: 'manage_edit_user'
  put 'manager/users/:user_id', to: 'managers#update', as: 'manage_update_user'
  delete 'manager/users/:user_id/delete', to: 'managers#delete', as: 'manage_delete_user'

  root 'main#home'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :photo_likeables, dependent: :destroy
  has_many :likes, through: :photo_likeables, source: :user
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :mode, presence: true, inclusion: { in: %w[Public Private], message: '%<value> is not a valid mode' }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = current_user.photos.new
  end

  def create
    @photo = current_user.photos.build photo_params
    if @photo.save
      flash[:notice] = 'Update Successfully'
      redirect_to profiles_photos_path
    else
      # flash[:alert] = 'There has been an error while updating image'
      flash[:alert] = @photo.errors.full_messages
      redirect_to new_photo_path
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if params[:save].present?
      if @photo.update(photo_params)
        flash[:notice] = 'Uploaded successfully'
        if current_user.role == 'manager'
          redirect_to manage_photo_path
        else
          redirect_to profiles_photos_path
        end
      else
        flash[:alert] = 'There has been an error when uploading photo'
        redirect_to edit_photo_path
      end
    elsif params[:delete].present?
      if @photo.destroy
        flash[:notice] = 'Deleted successfully'
        if current_user.role == 'manager'
          redirect_to manage_photo_path
        else
          redirect_to profiles_photos_path
        end
      else
        flash[:alert] = 'There has been an error when deleting photo'
        redirect_to edit_photo_path
      end
    else
      render 'photos/edit'
    end
  end

  def like
    @photo = Photo.find(params[:photo_id])
    @user = User.find(params[:user_id])
    @user.like(@photo, 'photo')
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: private_stream
      end
    end
  end

  private

  def private_stream
    private_target = "#{helpers.dom_id(@photo)} private_likes"
    turbo_stream.replace(private_target, partial: 'feeds/partials/likes',
                                         locals: { photo: @photo, type: 'photo',
                                                   like_status: current_user.liked?(@photo, 'photo') })
  end

  def photo_params
    params.require(:photo).permit(:title, :description, :mode, :image)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<div class="d-flex align-items-center justify-content-between border-bottom border-secondary-subtle mb-3">
  <nav class="navbar bg-white">
    <div class="container">
      <h2 class="navbar-brand profile-title">
        Edit Photo
      </h2>
    </div>
  </nav>
  <%= link_to "Back", profiles_photos_path, class: "btn rounded-1 pt-1 back-button text-decoration-none" %>
</div>

<div class="container" data-controller="photo">
  <%= form_with model: @photo, url: photo_path, method: :patch do |f| %>
    <div class="row align-items-center">
      <div class="col col-12 col-md-6">
        <div class="mb-3">
          <%= f.label :title, "Title", class: "form-label profile-title",
                      style: "font-size: 13px;" %>
          <%= f.text_field :title, class: "form-control", placeholder: "Photo title" %>
        </div>

        <%= f.label :mode, "Sharing mode", class: "form-label profile-title",
                    style: "font-size: 13px;" %>
        <%= f.select :mode, ["Public", "Private"], {}, class: "form-select" %>
      </div>

      <div class="col col-12 col-md-6">
        <div class="mb-3">
          <%= f.label :description, "Description", class: "form-label profile-title",
                      style: "font-size: 13px;" %>
          <%= f.text_area :description, class: "form-control", rows: "6", placeholder: "Photo description" %>
        </div>

      </div>
    </div>

    <div class="d-grid gap-4">
      <div class="rounded border-dark border-2 bg-light d-flex align-items-center justify-content-center position-relative"
           style="width: 200px; height: 200px; border-style: dashed"
           data-action="click->photo#clickUpload">
        <% if @photo.image.file.nil? %>
          <%= image_tag("upload.svg", style: "width: 50px; height: 50px", id: "blah_1") %>
        <% else %>
          <%= image_tag("upload.svg", class: "d-none", style: "width: 50px; height: 50px", id: "blah_1") %>
          <%= image_tag(@photo.image.url, class: "img-fluid", style: "width: 200px; height: 200px", id: "blah_2") %>
          <div style="width: 30px; height: 30px" id="blah_3" data-action="click->photo#changeImage">
            <%= image_tag("cancel.png",
                          style: "position: absolute; top: 5px; right: 5px; width: 20px; height: 20px") %>
          </div>
        <% end %>
      </div>
      <%= f.label :image, class: "d-none" %>
      <%= f.file_field :image, class: "d-none", data: { action: "change->photo#loadImage" } %>
      <div class="d-flex gap-3">
        <%= f.submit "Save", name: "save", class: "btn btn-success", style: "width: 100px" %>
        <%= f.submit "Delete", name: "delete", class: "btn btn-danger", style: "width: 100px" %>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<nav class="navbar bg-white border-bottom border-secondary-subtle mb-3">
  <div class="container">
    <h2 class="navbar-brand profile-title">
      New Photo
    </h2>
  </div>
</nav>

<div class="container" data-controller="photo">
  <%= form_with model: @photo, url: photos_path, method: :post do |f| %>
    <div class="row align-items-center">
      <div class="col col-12 col-md-6">
        <div class="mb-3">
          <%= f.label :title, "Title", class: "form-label profile-title",
                      style: "font-size: 13px;" %>
          <%= f.text_field :title, class: "form-control", placeholder: "Photo title" %>
        </div>

        <%= f.label :mode, "Sharing mode", class: "form-label profile-title",
                    style: "font-size: 13px;" %>
        <%= f.select :mode, ["Public", "Private"], {}, class: "form-select" %>
      </div>

      <div class="col col-12 col-md-6">
        <div class="mb-3">
          <%= f.label :description, "Description", class: "form-label profile-title",
                      style: "font-size: 13px;" %>
          <%= f.text_area :description, class: "form-control", rows: "6", placeholder: "Photo description" %>
        </div>

      </div>
    </div>

    <div class="d-grid gap-4">
      <div class="rounded border-dark border-2 bg-light d-flex align-items-center justify-content-center"
           style="width: 200px; height: 200px; border-style: dashed"
           data-action="click->photo#clickUpload">
        <%= image_tag("upload.svg", style: "width: 50px; height: 50px", id: "blah_1") %>
        <%= image_tag("upload.svg", class: "d-none img-fluid", style: "width: 200px, height: 200px", id: "blah_2") %>
      </div>
      <%= f.label :image, class: "d-none" %>
      <%= f.file_field :image, class: "d-none", data: { action: "change->photo#loadImage" } %>
      <%= f.submit "Save", class: "btn btn-success", style: "width: 150px; margin-left: 25px" %>
    </div>
  <% end %>
</div>