config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Photo and albums routes
  scope :users do
    resources :photos, :albums, except: %i[index show]
  end
  # Profile routes
  get '/profiles/photos', to: 'profiles#personalpagephoto'
  get '/profiles/albums', to: 'profiles#personalpagealbum'
  get '/profiles/followers', to: 'profiles#personalpagefollower'
  get '/profiles/followings', to: 'profiles#personalpagefollowing'
  # Public profile routes
  get '/profiles/:id/photos', to: 'public_profiles#photo', as: 'public_photo'
  get 'profiles/:id/albums', to: 'public_profiles#album', as: 'public_album'
  get 'profiles/:id/followings', to: 'public_profiles#following', as: 'public_followings'
  get 'profiles/:id/followers', to: 'public_profiles#follower', as: 'public_followers'
  # Feeds & Discovers routes
  get 'feeds/photos', to: 'feeds#photo', as: 'feed_photos'
  get 'feeds/albums', to: 'feeds#album', as: 'feed_albums'
  get 'discover/photos', to: 'discovers#photo', as: 'discover_photos'
  get 'discover/albums', to: 'discovers#album', as: 'discover_albums'
  # follow route
  patch '/follow/unfollow/:follower_id/:followed_id', to: 'follows#unfollow', as: 'unfollow'
  patch '/follow/:follower_id/:followed_id', to: 'follows#follow', as: 'follow'
  # like post route
  post '/users/:user_id/photos/:photo_id', to: 'photos#like', as: 'like_photo'
  post '/users/:user_id/album/:album_id', to: 'albums#like', as: 'like_album'
  # manager routes
  get 'manager/photos', to: 'managers#photo', as: 'manage_photo'
  get 'manager/albums', to: 'managers#album', as: 'manage_album'
  get 'manager/users', to: 'managers#user', as: 'manage_user'
  get 'manager/users/:user_id/edit', to: 'managers#edit', as: 'manage_edit_user'
  put 'manager/users/:user_id', to: 'managers#update', as: 'manage_update_user'
  delete 'manager/users/:user_id/delete', to: 'managers#delete', as: 'manage_delete_user'

  root 'main#home'
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def photo
    @users = current_user.followings
    @photos = Photo.where(user_id: @users.pluck(:id), mode: 'Public').page(params[:page]).per(4)
    render 'feeds/feeds'
  end

  def album
    @users = current_user.followings
    @albums = Album.where(user_id: @users.pluck(:id), mode: 'Public').page(params[:page]).per(4)
    render 'feeds/albums'
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/partials/_album.html.erb
<div class="col mb-3">
  <div class="card h-100 bg-light" style="max-width: 540px">
    <div class="row g-0 pt-3 pb-2 bg-light photo-card-font">
      <!--      Following user uploaded photo-->
      <div class="col-6 position-relative" data-bs-toggle="modal" data-bs-target="#<%= album.id %>" style="min-height: 250px">
        <%= image_tag(album.images[0].url, class: "img-fluid img-thumbnail rounded position-absolute bg-secondary",
                      style: "transform: skewY(8deg)") %>
        <%= image_tag(album.images[0].url, class: "img-fluid img-thumbnail rounded position-absolute bg-secondary",
                      style: "transform: skewY(4deg)") %>
        <%= image_tag(album.images[0].url, class: "img-fluid img-thumbnail position-absolute rounded bg-secondary") %>
      </div>
      <div class="col-6">
        <!--        Photo info-->
        <div class="card-body position-relative h-100">
          <% if user_signed_in? %>
            <% if request.env["REQUEST_PATH"].include?('discover') %>
              <div class="d-flex justify-content-end">
                <% if user.followers.ids.include?(current_user.id) %>
                  <%= button_to "following", unfollow_path(current_user, user), method: :patch,
                                class: "btn btn-outline-info text-white fbtn add-photo-album-button d-flex align-items-center",
                                style: " color: #3b5998; border-color: #3b5998; background-color: #3b5998; height: 20px" %>
                <% else %>
                  <%= button_to "follow", follow_path(current_user, user), method: :patch,
                                class: "btn btn-outline-info fbtn add-photo-album-button d-flex align-items-center",
                                style: " color: #3b5998; border-color: #3b5998; height: 20px" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <div class="align-items-center d-inline-flex mb-1">
            <!--            following user avatar-->
            <%= link_to public_album_path(user.id), style: "border: none", class: "bg-light d-flex align-items-center text-decoration-none" do %>
              <div class="me-2 mb-0 text-center avatar-header following-user-name-font">
                <% if user.avatar.file.nil? %>
                  <p class="mb-0 text-white"><%= user.fname[0] + user.lname[0] %></p>
                <% else %>
                  <%= image_tag(user.avatar.url, class: "img-thumbnail border-0 p-0 rounded-circle") %>
                <% end %>
              </div>
              <!--            following user name-->
              <p class="me-4 mb-0" style="font-weight: 700; color: #3b5998">
                <%= user.fname + ' ' + user.lname %>
              </p>
            <% end %>
          </div>
          <!--          Photo title-->
          <h5 class="card-title" style="font-weight: 700; font-size: 14px">
            <%= album.title %>
          </h5>
          <!--          photo description-->
          <p class="card-text text-start" style="font-weight: 400; line-height: 15px; max-width: 255px">
            <%= album.description %>
          </p>
          <!--          Photo footer-->
          <div class="d-flex justify-content-evenly align-items-center w-auto position-absolute"
               style="bottom: 10px; min-width: 200px">
            <% if user_signed_in? %>
              <%= render partial: 'feeds/partials/likes', locals: { photo: album, type: 'album', like_status: like_status } %>
            <% end %>
            <p class="card-text d-inline-flex ms-auto">
              <small class="text-body-secondary">
                <%= album.updated_at.in_time_zone("Asia/Ho_Chi_Minh").strftime("%I:%M %p %d/%m/%Y") %>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'layouts/partials/modalalbum', locals: { album: album } %>

app/views/feeds/partials/_buttons.html.erb
<div class="d-flex align-items-center justify-content-center g-0 pb-4">
  <% if request.env["REQUEST_PATH"].include?("feeds") %>
    <% if request.env["REQUEST_PATH"].include?("photos") %>
      <%= link_to "PHOTO", feed_photos_path, class: "btn feed-button px-0 left-button" %>
      <%= link_to "ALBUM", feed_albums_path, class: "btn feed-button px-0 border-dark right-button" %>
    <% else %>
      <%= link_to "PHOTO", feed_photos_path, class: "btn feed-button px-0 border-dark left-button-album" %>
      <%= link_to "ALBUM", feed_albums_path, class: "btn feed-button px-0 right-button-album" %>
    <% end %>
  <% else %>
    <% if request.env["REQUEST_PATH"].include?("photos") %>
      <%= link_to "PHOTO", discover_photos_path, class: "btn feed-button px-0 left-button" %>
      <%= link_to "ALBUM", discover_albums_path, class: "btn feed-button px-0 border-dark right-button" %>
    <% else %>
      <%= link_to "PHOTO", discover_photos_path, class: "btn feed-button px-0 border-dark left-button-album" %>
      <%= link_to "ALBUM", discover_albums_path, class: "btn feed-button px-0 right-button-album" %>
    <% end %>
  <% end %>
</div>

app/views/feeds/partials/_like_count.html.erb
<%= pluralize(photo.likes.count, "") %>

app/views/feeds/partials/_likes.html.erb
<div id="<%= "#{dom_id(photo)} private_likes" %>" data-controller="photo" class="d-inline-flex align-items-center">

  <% like_tweet = like_status ? "Unlike" : "Like" %>

  <% if type == 'album' %>
    <%= button_to like_album_path(user_id: current_user.id, album_id: photo.id), style: "border: none", class: "bg-light" do %>
      <% if like_tweet == "Unlike" %>
        <%= image_tag('heart_grey.svg', style: "height: 12px; width: 12.47px") %>
      <% elsif like_tweet == "Like" %>
        <%= image_tag('heart_white.svg', style: "height: 12px; width: 12.47px") %>
      <% end %>
    <% end %>
  <% elsif type == 'photo' %>
    <%= button_to like_photo_path(user_id: current_user.id, photo_id: photo.id), style: "border: none", class: "bg-light" do %>
      <% if like_tweet == "Unlike" %>
        <%= image_tag('heart_grey.svg', style: "height: 12px; width: 12.47px") %>
      <% elsif like_tweet == "Like" %>
        <%= image_tag('heart_white.svg', style: "height: 12px; width: 12.47px") %>
      <% end %>
    <% end %>
  <% end %>

  <p class="mb-0" style="font-size: 10px; font-weight: 400;color: #3b5998;">
    <%= render "feeds/partials/like_count", photo: photo %>
  </p>
</div>

app/views/feeds/partials/_photo.html.erb
<div class="col mb-3">
  <div class="card h-100 bg-light" style="max-width: 540px">
    <div class="row g-0 bg-light photo-card-font">
      <!--      Following user uploaded photo-->
      <div class="col-md-6" data-bs-toggle="modal" data-bs-target="#<%= photo.id %>">
        <%= image_tag(photo.image.url, class: "img-fluid rounded-start") %>
      </div>
      <div class="col-md-6">
        <!--        Photo info-->
        <div class="card-body position-relative h-100">
          <!--          follow button in discover-->
          <% if user_signed_in? %>
            <% if request.env["REQUEST_PATH"].include?('discover') %>
              <div class="d-flex justify-content-end">
                <% if user.followers.ids.include?(current_user.id) %>
                  <%= button_to "following", unfollow_path(current_user, user), method: :patch,
                                class: "btn btn-outline-info text-white fbtn add-photo-album-button d-flex align-items-center",
                                style: " color: #3b5998; border-color: #3b5998; background-color: #3b5998; height: 20px" %>
                <% else %>
                  <%= button_to "follow", follow_path(current_user, user), method: :patch,
                                class: "btn btn-outline-info fbtn add-photo-album-button d-flex align-items-center",
                                style: " color: #3b5998; border-color: #3b5998; height: 20px" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <div class="align-items-center d-inline-flex mb-1">
            <%= link_to public_photo_path(user.id), style: "border: none", class: "bg-light d-flex align-items-center text-decoration-none" do %>
              <!--            following user avatar-->
              <div class="me-2 mb-0 text-center avatar-header following-user-name-font">
                <% if user.avatar.file.nil? %>
                  <p class="mb-0 text-white"><%= user.fname[0] + user.lname[0] %></p>
                <% else %>
                  <%= image_tag(user.avatar.url, class: "img-thumbnail border-0 p-0 rounded-circle") %>
                <% end %>
              </div>
              <!--            following user name-->
              <p class="me-4 mb-0" style="font-weight: 700; color: #3b5998">
                <%= user.fname + ' ' + user.lname %>
              </p>
            <% end %>
          </div>
          <!--          Photo title-->
          <h5 class="card-title" style="font-weight: 700; font-size: 14px">
            <%= photo.title %>
          </h5>
          <!--          photo description-->
          <p class="card-text text-start" style="font-weight: 400; line-height: 15px; max-width: 255px">
            <%= photo.description %>
          </p>
          <!--          Photo footer-->
          <div class="d-flex justify-content-evenly align-items-center w-auto position-absolute"
               style="bottom: 10px; min-width: 200px">
            <% if user_signed_in? %>
              <%= render partial: 'feeds/partials/likes', locals: { photo: photo, type: 'photo', like_status: like_status } %>
            <% end %>
            <p class="card-text d-inline-flex ms-auto">
              <small class="text-body-secondary">
                <%= photo.updated_at.in_time_zone("Asia/Ho_Chi_Minh").strftime("%I:%M %p %d/%m/%Y") %>
              </small>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'layouts/partials/modalphoto', locals: { photo: photo } %>