config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Photo and albums routes
  scope :users do
    resources :photos, :albums, except: %i[index show]
  end
  # Profile routes
  get '/profiles/photos', to: 'profiles#personalpagephoto'
  get '/profiles/albums', to: 'profiles#personalpagealbum'
  get '/profiles/followers', to: 'profiles#personalpagefollower'
  get '/profiles/followings', to: 'profiles#personalpagefollowing'
  # Public profile routes
  get '/profiles/:id/photos', to: 'public_profiles#photo', as: 'public_photo'
  get 'profiles/:id/albums', to: 'public_profiles#album', as: 'public_album'
  get 'profiles/:id/followings', to: 'public_profiles#following', as: 'public_followings'
  get 'profiles/:id/followers', to: 'public_profiles#follower', as: 'public_followers'
  # Feeds & Discovers routes
  get 'feeds/photos', to: 'feeds#photo', as: 'feed_photos'
  get 'feeds/albums', to: 'feeds#album', as: 'feed_albums'
  get 'discover/photos', to: 'discovers#photo', as: 'discover_photos'
  get 'discover/albums', to: 'discovers#album', as: 'discover_albums'
  # follow route
  patch '/follow/unfollow/:follower_id/:followed_id', to: 'follows#unfollow', as: 'unfollow'
  patch '/follow/:follower_id/:followed_id', to: 'follows#follow', as: 'follow'
  # like post route
  post '/users/:user_id/photos/:photo_id', to: 'photos#like', as: 'like_photo'
  post '/users/:user_id/album/:album_id', to: 'albums#like', as: 'like_album'
  # manager routes
  get 'manager/photos', to: 'managers#photo', as: 'manage_photo'
  get 'manager/albums', to: 'managers#album', as: 'manage_album'
  get 'manager/users', to: 'managers#user', as: 'manage_user'
  get 'manager/users/:user_id/edit', to: 'managers#edit', as: 'manage_edit_user'
  put 'manager/users/:user_id', to: 'managers#update', as: 'manage_update_user'
  delete 'manager/users/:user_id/delete', to: 'managers#delete', as: 'manage_delete_user'

  root 'main#home'
end

app/models/albulm_likeable.rb
class AlbulmLikeable < ApplicationRecord
  belongs_to :user
  belongs_to :album
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :albulm_likeables, dependent: :destroy
  has_many :likes, through: :albulm_likeables, source: :user
  mount_uploaders :images, ImageUploader

  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :mode, presence: true, inclusion: { in: %w[Public Private], message: '%<value> is not a valid mode' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/liked_album.rb
class LikedAlbum < ApplicationRecord
end

app/models/liked_photo.rb
class LikedPhoto < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :photo_likeables, dependent: :destroy
  has_many :likes, through: :photo_likeables, source: :user
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 140 }
  validates :description, presence: true, length: { maximum: 300 }
  validates :mode, presence: true, inclusion: { in: %w[Public Private], message: '%<value> is not a valid mode' }
end

app/models/photo_likeable.rb
class PhotoLikeable < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  mount_uploader :avatar, AvatarUploader

  has_many :photos, dependent: :destroy
  has_many :albums, dependent: :destroy

  has_many :photo_likeables, dependent: :destroy
  has_many :likes_photos, through: :photo_likeables, source: :photo
  has_many :albulm_likeables, dependent: :destroy
  has_many :likes_albums, through: :albulm_likeables, source: :album

  def liked?(tweet, tweet_type)
    if tweet_type == 'photo'
      likes_photos.include?(tweet)
    elsif tweet_type == 'album'
      likes_albums.include?(tweet)
    end
  end

  def like(tweet, tweet_type)
    if tweet_type == 'photo'
      if likes_photos.include?(tweet)
        likes_photos.destroy(tweet)
      else
        likes_photos << tweet
      end
    elsif tweet_type == 'album'
      if likes_albums.include?(tweet)
        likes_albums.destroy(tweet)
      else
        likes_albums << tweet
      end
    end
  end

  # For users being followed
  has_many :followers_relationships, foreign_key: :followed_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :followers_relationships, source: :follower

  # For users who are following
  has_many :followings_relationships, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
  has_many :followings, through: :followings_relationships, source: :followed

  validates :fname, presence: true, length: { maximum: 25 }
  validates :lname, presence: true, length: { maximum: 25 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :role, presence: true
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def photo
    @users = current_user.followings
    @photos = Photo.where(user_id: @users.pluck(:id), mode: 'Public').page(params[:page]).per(4)
    render 'feeds/feeds'
  end

  def album
    @users = current_user.followings
    @albums = Album.where(user_id: @users.pluck(:id), mode: 'Public').page(params[:page]).per(4)
    render 'feeds/albums'
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home; end

  def feeds; end

  def discovers; end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discovers_helper.rb
module DiscoversHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Fotobook</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <%= render "layouts/partials/googlefont" %>
</head>
<body>
<%= render "layouts/partials/navbar" %>

<div class="container-fluid">
  <%= render "layouts/partials/logined" %>
</div>

<%= render "layouts/partials/displayAlerts" %>
</body>
</html>

app/views/layouts/partials/_3rdlogin.html.erb
<div class="d-flex form-signin w-75 m-auto bg-body-tertiary justify-content-around align-items-center border rounded border-ligh mb-3 mt-1">
  <img alt="Chrome-icon" width="50" height="50" src="<%= image_path("chrome.png") %>">
  <img alt="Facebook-icon" width="50" height="50" src="<%= image_path("facebook.png") %>">
  <img alt="Twitter-icon" width="50" height="50" src="<%= image_path("twitter.png") %>">
</div>

app/views/layouts/partials/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

app/views/layouts/partials/_displayAlerts.html.erb
<% if flash[:notice] %>
  <%= render "layouts/partials/alerts" %>
  <div class="alert alert-success d-flex align-items-center justify-content-between position-absolute bottom-0 end-0 w-25" role="alert">
    <div class="d-flex gap-1">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
        <use xlink:href="#check-circle-fill"/>
      </svg>
      <h6><%= flash[:notice] %></h6>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <%= render "layouts/partials/alerts" %>
  <div class="alert alert-warning d-flex align-items-center justify-content-between position-absolute bottom-0 end-0 w-25" role="alert">
    <div class="d-flex gap-1">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
        <use xlink:href="#exclamation-triangle-fill"/>
      </svg>
      <h6><%= flash[:alert] %></h6>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/partials/_errormessgaes.html.erb
<% if resource.errors.any? %>
  <%= render "layouts/partials/alerts" %>
  <div class="alert alert-warning d-flex flex-column align-items-center position-absolute bottom-0 end-0" role="alert">
    <div class="d-flex justify-content-between w-100 mb-3">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
        <use xlink:href="#exclamation-triangle-fill"/>
      </svg>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <%= render "devise/shared/error_messages", resource: resource %>
  </div>
<% end %>

app/views/layouts/partials/_googlefont.html.erb
<%# link to google font %>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link
  href="https://fonts.googleapis.com/css2?family=Lexend&family=Roboto:wght@400;500&display=swap"
  rel="stylesheet"/>

app/views/layouts/partials/_logined.html.erb
<% if request.env["REQUEST_PATH"].include?('users') && request.env["REQUEST_PATH"].exclude?('edit') &&
  request.env["REQUEST_PATH"].exclude?('manager') %>
  <%= yield %>
<% else %>
  <section id="newsFeed" class="bg-light">
    <div class="row me-0 bg-light" style="height: 100%">
      <div class="col-2 h-100 pt-5">
        <div class="d-grid gap-2 col-6 mx-md-auto m-0 text-start">
          <% if user_signed_in? && request.env["REQUEST_PATH"].exclude?("manager") %>
            <% if request.env["REQUEST_PATH"].include?("feeds") %>
              <%= link_to "Feeds", feed_photos_path,
                          class: "btn fbtn text-start p-0 text-decoration none", style: "color: #3b5998" %>
            <% else %>
              <%= link_to "Feeds", feed_photos_path,
                          class: "btn fbtn text-start p-0 text-decoration none" %>
            <% end %>
            <% if request.env["REQUEST_PATH"].include?("discover") %>
              <%= link_to "Discover", discover_photos_path,
                          class: "btn fbtn text-start p-0 text-decoration none", style: "color: #3b5998" %>
            <% else %>
              <%= link_to "Discover", discover_photos_path,
                          class: "btn fbtn text-start p-0 text-decoration none" %>
            <% end %>
          <% elsif request.env["REQUEST_PATH"].include?("manager") %>
            <% if request.env["REQUEST_PATH"].include?("photos") %>
              <%= link_to "Manage Photos", manage_photo_path,
                          class: "btn fbtn text-start p-0 text-decoration none", style: "color: #3b5998" %>
            <% else %>
              <%= link_to "Manage Photos", manage_photo_path,
                          class: "btn fbtn text-start p-0 text-decoration none" %>
            <% end %>
            <% if request.env["REQUEST_PATH"].include?("albums") %>
              <%= link_to "Manage Albums", manage_album_path,
                          class: "btn fbtn text-start p-0 text-decoration none", style: "color: #3b5998" %>
            <% else %>
              <%= link_to "Manage Albums", manage_album_path,
                          class: "btn fbtn text-start p-0 text-decoration none" %>
            <% end %>
            <% if request.env["REQUEST_PATH"].include?("users") %>
              <%= link_to "Manage Users", manage_user_path,
                          class: "btn fbtn text-start p-0 text-decoration none", style: "color: #3b5998" %>
            <% else %>
              <%= link_to "Manage Users", manage_user_path,
                          class: "btn fbtn text-start p-0 text-decoration none" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-8 bg-white pt-4 border border-light rounded-bottom overflow-auto" style="height: 90vh">
        <%= yield %>
      </div>
      <div class="col-2 h-100 pt-5"></div>
    </div>
  </section>
<% end %>

app/views/layouts/partials/_modalalbum.html.erb
<div class="modal fade" id="<%= album.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fbtn text-dark" style="font-size: 20px" id="exampleModalLabel"><%= album.title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body justify-content-center">
        <%#= image_tag(album.images[0].url, class: "img-fluid rounded w-100 h-100") %>
        <div id="Indicators<%= album.id %>" class="carousel slide">
          <div class="carousel-indicators">
            <% album.images.each_with_index do |image, counter| %>
              <%= render partial: "albums/partials/carousel", locals: { image: image, counter: counter, id: album.id } %>
            <% end %>
          </div>
          <div class="carousel-inner">
            <% album.images.each_with_index do |image, counter| %>
              <%= render partial: 'albums/partials/photos', locals: { image: image, counter: counter } %>
            <% end %>
          </div>
          <!--          carousel indicator-->
          <% album.images.each_with_index do |image, counter| %>
            <%= render partial: "albums/partials/carouselFooter", locals: { image: image, counter: counter, id: album.id } %>
          <% end %>
        </div>
      </div>
      <div class="modal-footer justify-content-start">
        <p class="fbtn text-dark" style="font-weight: 400; font-size: 14px"><%= album.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_modalphoto.html.erb
<div class="modal fade" id="<%= photo.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title fbtn text-dark" style="font-size: 20px" id="exampleModalLabel"><%= photo.title %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body justify-content-center">
        <%= image_tag(photo.image.url, class: "img-fluid rounded w-100 h-100") %>
      </div>
      <div class="modal-footer justify-content-start">
        <p class="fbtn text-dark" style="font-weight: 400; font-size: 14px"><%= photo.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/partials/_navbar.html.erb
<header id="header" class="position-sticky">
  <nav
    class="navbar navbar-expand-md d-flex py-3"
    style="font-family: 'Lexend', sans-serif; background-color: #3b5998"
  >
    <div class="container-fluid">
      <div class="navbar-brand me-0">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="30"
          height="30"
          fill="currentColor"
          class="bi bi-apple mb-1 link-dark"
          viewBox="0 0 16 16"
        >
          <path
            d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z"
            />
          <path
            d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z"
            />
        </svg>
        <% if user_signed_in? %>
          <% if current_user.role == "manager" %>
            <%= link_to "Fotobook Admin", manage_photo_path, class: "navbar-brand link-light" %>
          <% else %>
            <%= link_to "Fotobook", feed_photos_path, class: "navbar-brand link-light" %>
          <% end %>
        <% else %>
          <%= link_to "Fotobook", discover_photos_path, class: "navbar-brand link-light" %>
        <% end %>
      </div>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav container-fluid pe-0">
          <li class="nav-item mt-1">
            <div class="container-fluid">
              <form class="d-flex" role="search">
                <input
                  class="form-control me-2"
                  type="search"
                  placeholder="Search"
                  aria-label="Search"
                  />
                <button class="btn btn-outline-light" type="submit">
                  Search
                </button>
              </form>
            </div>
          </li>
          <% if current_user %>
            <li class="nav-item ps-3 d-inline-flex align-items-center ms-md-auto">
              <div class="me-2 mb-0 text-center avatar-header">
                <p class="mb-0">
                  <%#= current_user.fname[0] + current_user.lname[0] %>
                  <% if current_user.avatar.file.nil? %>
                    <%= image_tag("user-solid.svg", class: "img-thumbnail border-0 p-0 rounded-circle") %>
                  <% else %>
                    <%= image_tag(current_user.avatar.url, class: "img-thumbnail border-0 p-0 rounded-circle") %>
                  <% end %>
                </p>
              </div>
              <p class="text-light me-4 mb-0">
                <%= link_to current_user.fname + " " + current_user.lname, profiles_photos_path,
                            class: "text-decoration-none", style: "color: inherit" %></p>
              <%= link_to "Logout", destroy_user_session_path, class: "nav-link link-light active" %>
            </li>
          <% else %>
            <li class="nav-item ms-md-auto ps-3">
              <%= link_to "Login", new_user_session_path, class: "nav-link link-light active" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>